# Rustfmt Configuration - Strict Rust Formatting
# https://rust-lang.github.io/rustfmt/
# Copy to project root as rustfmt.toml
# Note: Some options require nightly Rust

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Imports
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Formatting style
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
struct_lit_single_line = true

# Function signatures
fn_params_layout = "Tall"
fn_args_layout = "Tall"

# Comments
comment_width = 80
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80

# Strings
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

# Match arms
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# Other
use_small_heuristics = "Default"
use_field_init_shorthand = true
use_try_shorthand = true
force_multiline_blocks = false
overflow_delimited_expr = false
trailing_comma = "Vertical"
trailing_semicolon = true
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
short_array_element_width_threshold = 10
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false

# Unstable features (require nightly)
# unstable_features = true
# blank_lines_upper_bound = 1
# blank_lines_lower_bound = 0
# condense_wildcard_suffixes = true
# format_generated_files = true
# hex_literal_case = "Upper"
# reorder_impl_items = true
# struct_field_align_threshold = 0
# enum_discrim_align_threshold = 0
